import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

import Hello from '@/components/Hello'
import NewConcepts from '@/components/NewConcepts'
import ComponentWrapper from '@/components/ComponentWrapper'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Components zexample</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Fundamentals Components example</h1>
        <ComponentWrapper textColor='Blue'>
          <Hello/>
          <NewConcepts concept="Naming the component the same as the file"/>
          <NewConcepts concept="Weird babel errors that I have"/>
        </ComponentWrapper>
      </main>
    </>
  )
}
