import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import Button from 'react-bootstrap/Button';

const inter = Inter({ subsets: ['latin'] })

import ComponentLibrariesList from '@/components/ComponentLibrariesList';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Container>
          <Row>
            <h1>Example of Using Bootstrap</h1>
          </Row>
          <Row>
            <Col>
              <h4>Available component libraries</h4>
              <ComponentLibrariesList/>
              <Button variant='dark'>Coolest button ever</Button>
            </Col>
          </Row>
        </Container>
      </main>
    </>
  )
}
