import Head from 'next/head'
import Box from '@mui/material/Box';
import Container from '@mui/material/Container';
import Typography from '@mui/material/Typography';



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Container maxWidth="sm">
          <Box sx={{my:4}}>
            <Typography variant='h2'>
              First experience with material ui
            </Typography>
            <Typography variant="body1">
              This looks okay
            </Typography>
          </Box>
        </Container>
      </main>
    </>
  )
}
